### ISSUE TITLE
New Icon: Patreon

### ISSUE THREAD

**Issue by sdixon194** [Automattic/social-logos#101]
[Per this request here](https://github.com/Automattic/jetpack/issues/14122), so we can add the logo to the social menu and social icons widget.

[Patreon brand guide](https://www.patreon.com/brand). 

Thanks!

**Comment by pablohoneyhoney** [comment]
Here a first pass if helpful for testing. The path might need further simplification. [social-patreon.svg.zip](https://github.com/Automattic/social-logos/files/5822916/social-patreon.svg.zip)
<img width="600" alt="social-patreon" src="https://user-images.githubusercontent.com/25516611/104779075-73640d80-574c-11eb-90b0-a798bd2b2ebd.png">

**Comment by folletto** [comment]
Sounds good: simplification is rather easy, so we can do once we make the PR. If I remember correctly the build system also strips automatically the `fill` attributes to allow coloring.

One thing: it seems smaller in the 24px grid compared to the other icons in the set. We probably need to make sure it's optically the same size too.

**Comment by pablohoneyhoney** [comment]
Yes, the area needs to be 24, not necessarily the icon object itself. But certainly needs to pair nicely with the surrounding icons.

**Comment by porada** [comment]
Just published `social-logos@2.2.0` with the new Patreon icon.
