### ISSUE TITLE
New Icon: TikTok

### ISSUE THREAD

**Issue by sdixon194** [Automattic/social-logos#102]
We have quite a few [requests to add the TikTok logo](https://github.com/Automattic/jetpack/issues/13765), so we can add the logo to the social menu and social icons widget.

Wasn't able to find a press kit or brand guide. The best I could find was [this third party source on the logo](https://www.logaster.com/blog/tiktok-logo/).

Although another comment in the previous issue [found this SVG](https://www.noff.com.au/wp-content/themes/noff/images/tiktok.svg).

[TikTok contact page](https://www.tiktok.com/contact?lang=en).

Thanks!

**Comment by davewhitley** [comment]
There doesn't appear to be an official icon resource, so this one should be good enough:

![Screen Shot 2021-01-26 at 1 34 12 PM](https://user-images.githubusercontent.com/618551/105895501-382ecd80-5fdb-11eb-92c1-9ae67c958252.png)
![Screen Shot 2021-01-26 at 1 34 07 PM](https://user-images.githubusercontent.com/618551/105895506-382ecd80-5fdb-11eb-9a76-79eacf3f53fb.png)

SVG Attachment (normal and alt):

https://cloudup.com/cHFNpGuzpSi
