### ISSUE TITLE
New Icon: Copy post url icon. 

### ISSUE THREAD

**Issue by spsiddarthan** [Automattic/social-logos#111]
I am working on an [issue](https://github.com/Automattic/jetpack/issues/12927), where we decided that we are going to be adding a button that will copy a post's URL to the clipboard and need an icon for it. 

This is the icon that needs to be added: https://developer.wordpress.org/resource/dashicons/#admin-links

Screenshot: 

<img width="514" alt="Screenshot 2022-01-04 at 4 38 35 PM" src="https://user-images.githubusercontent.com/6594561/148050397-77994309-d617-4e89-9e60-4c5be551bcf6.png">

I couldn't find an in-house SVG for the copy link icon,  perhaps we can create one, or if it's allowed download a freely available SVG for a similar-looking copy link icon (not sure if we can use SVG's from other websites, so not pasting them here as of now).

**Comment by kellychoffman** [comment]
Hi! This repo is meant to be social media icons only. I would suggest utilizing [gridicons](http://automattic.github.io/gridicons/) instead, which has a link icon.

**Comment by spsiddarthan** [comment]
@eeeeevon13  @kellychoffman,

Disregard my previous comment, looks like I and @eeeeevon13 commented around the exact same time. :) 

Thanks for the links to the WordPress Design Library, I will explore that.

**Comment by spsiddarthan** [comment]
I just realized that I will still need to add the updated icon to the same repository, but technically this is not a social icon,  but a generic one and we need to decide if we can have this one added to this repository.

**Comment by pablinos** [comment]
> This repo is meant to be social media icons only

Hi @kellychoffman, I thought that might be the case, but this repo also has a print icon which is available in Gridicons too. 

If we swap to using Gridicons, I'm not sure what that will do to the size of the code that's loaded. We'll end up loading another font for this icon. We could do that only if the link item is displayed, which would help.

**Comment by spsiddarthan** [comment]
> Jetpack is trying to move to using the latest icon set in the [WordPress Design Library.](e4tLacmlPuZV47l7901FEs-fi-5415%3A23317) You can grab the proper icons [here](e4tLacmlPuZV47l7901FEs-fi-5415%3A23317) going forward and I've attached the link icon you need. [link.zip](https://github.com/Automattic/social-logos/files/7815356/link.zip)

We got the correct updated icons to use from @eeeeevon13.

Hi @kellychoffman, 

Just following up on this issue. 

However, we would need to still add that icon to this repository, else we would end up using a new font system just for this icon.  Please check [this comment of mine](https://github.com/Automattic/social-logos/issues/111#issuecomment-1005707889) from the same issue.

Let us know if that changes anything.  If we still shouldn't be adding the icon to this repo, we will find something out. 

cc: @pablinos

**Comment by kellychoffman** [comment]
Makes sense to add the link icon to this repo, since its inline with how we utilize the print and share icons. 

@davewhitley: could you help them out with that process?

**Comment by spsiddarthan** [comment]
Thank you so much, @davewhitley  and @kellychoffman 

 I have a PR open with the Gridicons, but need to update it to the one specified [here](https://github.com/Automattic/social-logos/issues/111#issuecomment-1005705261), I will do that and request for a PR review.

**Comment by imh0ng** [comment]
https://github.com/imh0ng/jetpack-sharing-button-copy-link-add
I have created a solution to add a Copy Link button to the Jetpack Share button.
