### ISSUE TITLE
Change Digg icon

### ISSUE THREAD

**Issue by drw158** [Automattic/social-logos#19]
As far as I can tell, Digg does not use the thumbs up icon anywhere anymore.

Because this repo is for logos, I suggest that we change the icon to one similar to their favicon:

![screen shot 2016-02-04 at 12 17 10 pm](https://cloud.githubusercontent.com/assets/618551/12824926/3c6ae88e-cb39-11e5-96be-16d01f311a68.png)

**Comment by drw158** [comment]
I couldn't find an official resource anywhere.

**Comment by jasmussen** [comment]
No no, Digg absolutely still uses the hand. Check this URL:

http://digg.com/video/grandmaster-vs-park-player

it's also inside their reader:

![screen shot 2016-02-18 at 09 54 07](https://cloud.githubusercontent.com/assets/1204802/13138165/b7388c82-d625-11e5-84ef-3add2e3bd032.png)

It's certainly true this repo is for logos that can be used for importers and exporters, but if it's ever to be useful in places like social sharing links, we're going to have to add some edgecase logos.

It is possible though that Digg has pivoted so far that you can't even share links to it anymore, in which case yes the thumb should be replaced by the digg logo.

**Comment by drw158** [comment]
Ah I see, I somehow missed the thumb while looking through their site.

I did some looking, and I can't find anything about their sharing buttons. On their website, they say they are still working on a new API, but that was updated in 2012.

The wpcom support docs don't mention digg, but I did find that Jetpack can embed a digg sharing button with a shortcode. Not sure if that uses an icon, or if it still works.

It looks like we don't need it at all on WordPress.com, but there's a chance Jetpack might use Genericons for the shortcode?

Either way I think we are pretty safe with removing the from this set. What do you think?

**Comment by jasmussen** [comment]
> It looks like we don't need it at all on WordPress.com, but there's a chance Jetpack might use Genericons for the shortcode?

We're looking into removing Genericons from Jetpack though, and replacing it with this.

**Comment by drw158** [comment]
Ok, I just tested the digg shortcode on my Jetpack site. 

It doesn't seem to do anything at all. The support doc has no instructions on how to use it:

https://jetpack.me/support/shortcode-embeds/

Not sure why it's still in the support doc. I say we just remove digg from this iconset.

**Comment by drw158** [comment]
Ok, I just asked Support. They have deactivated the digg shortcode indefinitely since the digg API is no longer. I feel ok about removing the icon.

**Comment by jasmussen** [comment]
In that case, yeah certainly remove the thumbs up! :+1: ;)

However we should also remember to report this upstream to the Jetpack folks so it can be removed from Jetpack.
