### ISSUE TITLE
New Icon: 500px

### ISSUE THREAD

**Issue by jacquesvoogt** [Automattic/social-logos#36]
Hi Guys

Can you add the 500px logo or explain to me how to add it?

Regards

**Comment by rickcurran** [comment]
The 500px logo appears to be in now so this should be closed I think.

**Comment by jacquesvoogt** [comment]
Sweet. I have since moved on to other platforms. Closing on your recommendation.

**Comment by rickcurran** [comment]
@jacquesvoogt Sorry, I'm actually mistaken, there isn't actually an icon for 500px in there after all. You can just leave this closed though and I'll do a PR for it myself.
