### ISSUE TITLE
Build: vulnerabilities in `package-lock.json` (not our direct)

### ISSUE THREAD

**Issue by folletto** [Automattic/social-logos#59]
After I landed https://github.com/Automattic/social-logos/pull/58 I also included `package-lock.json` which is a new feature of npm 5.x.

![screen shot 2018-02-01 at 17 47 49](https://user-images.githubusercontent.com/4389/35694080-0b3aa88a-0778-11e8-8e4d-5c467769a3c4.png)

This however means that now even we directly don't have any vulnerable package, some of the packages we use trigger it in the dependency tree.

Namely:

* `handlebars.js`(v2.0.0 vulnerable) — loaded by `grunt-svgstore`
* `UglifyJS2` (v2.3.6 vulnerable) — loaded by `handlebars.js`

Which means:

`grunt-svgstore` → `handlerbars.js` → `UglifyJS2`

Which reduces the issue to just `grunt-svgstore`. 

As far as I understand `grunt-svgstore` uses it to generate the documentation file. All the vulnerabilities seem of the "remote attacker" type, thus not a scenario we'll ever be into with this component: for us it's generated statically, and it's not part of the live React component.

Note that `grunt-svgstore` is currently stating on the [readme](https://github.com/FWeinb/grunt-svgstore/blob/682e5cfbb08494c2e9e4c32000a0cc7864b7de80/README.md) "I am looking for a maintainer who would like to take over this plugin", so it's unlikely to get updated.

---

Note: I think this impacts https://github.com/Automattic/gridicons and https://github.com/WordPress/dashicons as they both use `grunt-svgstore`, they just don't know yet as `package-lock.json` hasn't been pushed to the repo.

**Comment by gwwar** [comment]
Let's remove the svgstore dependency, it looks like we use it to generate an svg document (which is unused by the the published npm module). From the output we can use something else, or create this ourselves.

**Comment by gwwar** [comment]
@jasmussen @folletto Out of curiosity where is the [svg-sprite](svg document) being used? If we don't need it we can remove the task and dependency.

**Comment by jasmussen** [comment]
I don't know that the SVG-sprite is actually being used at all. 

Pretty sure it's a leftover from when we thought that was the primary way we thought we'd use SVG icons back in the day, due to caching and perf reasons. But other solutions have presented themselves. I think we can probably remove it.

**Comment by gwwar** [comment]
@jasmussen nice! I love it when we can delete code.

**Comment by folletto** [comment]
I don't know if it's used at all, so that's good to hear.

@jasmussen  Is it the same for Gridicons and Dashicons?

**Comment by folletto** [comment]
I don't know if it's used at all, so that's good to hear.

It might only be used in... the documentation page of the icon set itself: http://automattic.github.io/social-logos/

@jasmussen  Is it the same for Gridicons and Dashicons?

**Comment by jasmussen** [comment]
Yes indeed, it seems like it's only used in the demo page. Seems like we can do something else for that. And yes, afaik same for gridicons and dashicons.

**Comment by folletto** [comment]
"Fixed" in #61
