### ISSUE TITLE
Update icon: Medium

### ISSUE THREAD

**Issue by andfinally** [Automattic/social-logos#69]
We need to update our Medium icon to match their latest [branding](https://medium.design/logos-and-brand-guidelines-f1a01a733592). We use this icon in the importers section https://wordpress.com/settings/import/[site].wordpress.com.

![image](https://user-images.githubusercontent.com/1647564/46873989-f5f41900-ce2f-11e8-88e1-b8dd35fa4546.png)

![image](https://user-images.githubusercontent.com/1647564/46874142-53886580-ce30-11e8-92f7-2f9d08918b45.png)

I have an SVG for this icon from Medium's brand guidelines page (attached), but unfortunately I don't have the SVG skills to tweak it for inclusion in this package.

[Monogram.svg.zip](https://github.com/Automattic/wp-calypso/files/2473354/Monogram.svg.zip)

**Comment by andpiazza** [comment]
great catch @andfinally .

**Comment by dezzie** [comment]
In reference to this PR https://github.com/Automattic/social-logos/pull/71

(the comment I left over there is the same here, no need to re-read)

https://github.com/Automattic/social-logos/pull/71

**Comment by dezzie** [comment]
Also linking to this issue that's looking at the same thing so we can close out both: https://github.com/Automattic/wp-calypso/issues/27816
