### ISSUE TITLE
Support Mastadon

### ISSUE THREAD

**Issue by PanderMusubi** [Automattic/social-logos#82]
Please support Mastadon logo, see https://commons.wikimedia.org/wiki/File:Mastodon_Logotype_(Simple).svg

**Comment by lizkarkoski** [comment]
Another request to add Mastadon integration with Publicize auto sharing. 
https://wordpress.com/forums/topic/post-automatically-to-mastodon/?view=all

**Comment by lizkarkoski** [comment]
One more: https://wordpress.com/forums/topic/mastodon-verification-html/?view=all#post-3884601

**Comment by lizkarkoski** [comment]
+1 for this from Twitter: https://twitter.com/jonathanwthomas/status/1589698225862193152

**Comment by jeherve** [comment]
This was implemented in #115.

Noting that some of the requests referenced above seem to wish for specific features, like Publicize to Mastodon. This is not an option yet. To follow our progress on this issue, you can follow https://github.com/Automattic/jetpack/issues/7790
