### ISSUE TITLE
Remove built files from git

### ISSUE THREAD

**Issue by ockham** [Automattic/social-logos#85]
Do we have to check built files into git? I just filed a PR (#84)  to remove an obsolete logo, and it was really hard to tell which files I needed to remove manually. Just removing what I thought was the 'source of truth' (in `sources/svg/`) didn't cut itm, nor did re-running the build afterwards.

Ideally, built files should only be included with the published npm, but not in the git repo IMO.

**Comment by tbradsha** [comment]
Handled in Automattic/jetpack#36964.
